### ISSUE TITLE
响应式方案

### ISSUE THREAD

**Issue by travelk** [travelk/blog#12]
1.js动态修改html根元素字体
```js
(function() {
    var html = document.documentElement;
    var setFontSize = function() {
        document.body.setAttribute('style', 'max-width: 750px; margin: 0 auto;')
        var width = html.offsetWidth;
        if (width >= 750) {
            html.style.fontSize = 32 + 'px'
        } else {
            html.style.fontSize = 16 * (width / 375) + 'px'
        }
    };
    var timer;
    var setDelay = function() {
        return clearTimeout(timer), (timer = setTimeout(setFontSize, 150));
    }
    window.addEventListener('pageshow', function(evt) {
        return evt.persisted && setDelay();
    });
    window.addEventListener('resize', setDelay);
    setFontSize();
})();
```
2.媒体查询
```css
@media screen and (min-width: 320px) {
    html {font-size: 14px;}
}
 
@media screen and (min-width: 360px) {
    html {font-size: 16px;}
}
 
@media screen and (min-width: 400px) {
    html {font-size: 18px;}
}
 
@media screen and (min-width: 440px) {
    html {font-size: 20px;}
}
 
@media screen and (min-width: 480px) {
    html {font-size: 22px;}
}
 
@media screen and (min-width: 640px) {
    html {font-size: 28px;}
}
```
