### ISSUE TITLE
common.css

### ISSUE THREAD

**Issue by travelk** [travelk/blog#14]
```css
html,
body {
  font-family: "Helvetica Neue",Helvetica,"PingFang SC","Hiragino Sans GB","Microsoft YaHei","微软雅黑",Arial,sans-serif;
  font-size: 14px;
  height: 100%;
}
a {
  outline: none;
  text-decoration: none;
}
::-ms-clear,
::-ms-reveal {
  display:none;
}
ul {
  padding: 0;
  list-style: none;
}
.bold {
  font-weight: 700;
}
.text-center {
  text-align: center;
}
.pointer {
  cursor: pointer;
}
.flex {
  display: flex;
}
.flex-center {
  display: flex;
  justify-content: center;
  align-items: center;
}
.flex-middle {
  display: flex;
  align-items: center;
}
.flex-between {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.flex-item {
  flex: 1;
  min-width: 0;
}
```
