### ISSUE TITLE
移动端1px实现

### ISSUE THREAD

**Issue by travelk** [travelk/blog#7]
```css
/*移动端1px实现*/
.border-top:after {
    content: '';
    position: absolute;
    top: 0;
    right: auto;
    bottom: auto;
    left: 0;
    height: 1px;
    width: 100%;
    background-color: #e7e7e7;
    display: block;
    z-index: 15;
    -webkit-transform-origin: 50% 0;
    transform-origin: 50% 0;
}

.border-bottom:after {
    content: '';
    position: absolute;
    top: auto;
    right: auto;
    bottom: 0;
    left: 0;
    height: 1px;
    width: 100%;
    background-color: #e7e7e7;
    display: block;
    z-index: 15;
    -webkit-transform-origin: 50% 100%;
    transform-origin: 50% 100%;
}

@media only screen and (-webkit-min-device-pixel-ratio:2) {
    .border-top:after,
    .border-bottom:after {
        -webkit-transform: scaleY(.5);
        transform: scaleY(.5)
    }
}

@media only screen and (-webkit-min-device-pixel-ratio:3) {
    .border-top:after,
    .border-bottom:after {
        -webkit-transform: scaleY(.33);
        transform: scaleY(.33)
    }
}

.border-left:after {
    content: '';
    position: absolute;
    top: 0;
    right: auto;
    bottom: 0;
    left: 0;
    height: 100%;
    width: 1px;
    background-color: #e7e7e7;
    display: block;
    z-index: 15;
    -webkit-transform-origin: 0 50%;
    transform-origin: 0 50%;
}

.border-right:after {
    content: '';
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: auto;
    height: 100%;
    width: 1px;
    background-color: #e7e7e7;
    display: block;
    z-index: 15;
    -webkit-transform-origin: 100% 50%;
    transform-origin: 100% 50%;
}

@media only screen and (-webkit-min-device-pixel-ratio:2) {
    .border-left:after,
    .border-right:after {
        -webkit-transform: scaleX(.5);
        transform: scaleX(.5)
    }
}

@media only screen and (-webkit-min-device-pixel-ratio:3) {
    .border-left:after,
    .border-right:after {
        -webkit-transform: scaleX(.33);
        transform: scaleX(.33)
    }
}

.radius-border {
    position: relative;
    -webkit-border-radius: 5px;
    border-radius: 5px;
    text-align: center;
    line-height: 42px;
}

.radius-border:before {
    content: '';
    position: absolute;
    top: -50%;
    bottom: -50%;
    left: -50%;
    right: -50%;
    border: 1px solid #eee;
    border-radius: 10px;
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
}
```
